version: "3.8"

services:
  # Test Database Only - Main database will be Neon PostgreSQL
  postgres-test:
    image: postgres:15-alpine
    container_name: turbo-fullstack-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: turbo_fullstack_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
